tatiana5_docsviewer:
    path: /{mode}/{seoname}/{attach_id}.{extension}
    defaults: { _controller: tatiana5.docsviewer.docs:documents, seoname:'' }
    requirements:
        mode: documents
        attach_id: \d+
        extension: \w+
